=== johndpjr/AgTern/data/companies/AgTernScrapeConfigSchema.json
{
  "$schema": "http://json-schema.org/schema",
  "title": "AgTern Company Scrape Configuration Schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string",
      "enum": [ "AgTernScrapeConfigSchema.json" ]
    },
    "company": {
      "type": [ "object", "string" ],
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [ "name" ]
    },
    "links": {
      "type": "object",
      "patternProperties": {
        ".*": {
          "type": "string",
          "format": "uri"
        }
      },
      "required": [ "home", "internships" ]
    },
    "xpaths": {
      "type": "object",
      "patternProperties": {
        ".*": {
          "type": "string"
        }
      }
    },
    "regexes": {
      "type": [ "object", "string" ],
      "patternProperties": {
        ".*": {
          "type": "object",
          "properties": {
            "pattern": {
              "type": "string",
              "format": "regex"
            },
            "group": {
              "type": "integer"
            },
            "format": {
              "type": "string"
            },
            "default": {
              "type": "string"
            },
            "ascii": {
              "type": "boolean"
            },
            "dot_all": {
              "type": "boolean"
            },
            "ignore_case": {
              "type": "boolean"
            },
            "locale": {
              "type": "boolean"
            },
            "multiline": {
              "type": "boolean"
            },
            "verbose": {
              "type": "boolean"
            }
          },
          "required": [ "pattern" ],
          "additionalProperties": false
        }
      },
      "format": "regex"
    },
    "unique": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [ "$schema", "company", "links" ],
  "additionalProperties": false
}

=== johndpjr/AgTern/data/companies/_Example.json
{
  "$schema": "AgTernScrapeConfigSchema.json",
  "company": {
    "name": "Example Company"
  },
  "links": {
    "home": "https://www.example.com/",
    "internships": "https://www.example.com/search/?category=internships"
  },
  "xpaths": {
    "title": "//xpath/to/internship/titles",
    "company_job_id": "//xpath/to/internship/ids",
    "posting_link": "//xpath/to/posting/links/@href",
    "description": "//xpath/to/internship/descriptions"
  },
  "regexes": {
    "title": {
      "pattern": "(regex for title)",
      "ignore_case": true,
      "multiline": false
    },
    "company_job_id": "(regex for company_job_id)"
  },
  "unique": [
    "company_job_id",
    "posting_link"
  ]
}
